##########################################
### Include your secrets here for both ###
###   Home Assistant and ESPHome       ###
##########################################

# Example
some_password: Hunter2