##################################################################
### Change the Substitution Keys below to customize this board ###
##################################################################

substitutions:
    device_name: template-board                               # Device name with hyphens substituted for spaces.
    device_entity: template_board                             # Device name with underscores substituted for spaces.
    device_description: Template for D1Mini-32 sensor boards  # Device description, shown on ESPHome Dashboard
    friendly_name: Template Board                             # Device name, human-readable with spaces allowed.
    ipaddress: 192.168.86.180                                 # Static IP address for this device. Comment out the manual_ip section to use DHCP


###############################################################################
###  Note: Entries beginning with !secret reference keys from secrets.yaml  ###
###        Place the following in /config/esphome/secrets.yaml to use       ###
###            the /config/secrets.yaml file in your ESPHome code:          ###
###                  <<: !include ../secrets.yaml                           ###
###############################################################################

<<: !include common/common.yaml

# ESPHome Core config https://esphome.io/components/esphome.html
esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP32
  board: wemos_d1_mini32

# Enable Home Assistant API https://esphome.io/components/api.html
api:
  encryption:
    key: !secret template_crypt_key